# Generated by Django 5.0.2 on 2024-03-12 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionIntCO2e',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tco2', models.IntegerField()),
                ('diesel_generator', models.BigIntegerField()),
                ('gas', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GHGEmissionInOman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_ghg_emission', models.BigIntegerField()),
                ('power_consumption', models.BigIntegerField()),
                ('renewable_energy_penetration', models.IntegerField()),
                ('co2_emission', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MWH',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diesel_generators', models.FloatField()),
                ('gas', models.FloatField()),
                ('solar', models.FloatField()),
                ('onshore_wind', models.FloatField()),
                ('gas_with_ccs', models.FloatField()),
                ('nuclear', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField()),
                ('population', models.BigIntegerField()),
            ],
        ),
    ]
