# Generated by Django 5.0.2 on 2024-03-12 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ghgemissioninoman',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
