# Generated by Django 5.0.2 on 2024-03-12 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_ghgemissioninoman_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='mwh',
            name='year',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
